import React from 'react';

const countries = [
  {
    label: "An Giang",
    value: "An Giang",
    flag: "🇻🇳",
    latlng: [10.3864, 105.4358],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Bà Rịa-Vũng Tàu",
    value: "Bà Rịa-Vũng Tàu",
    flag: "🇻🇳",
    latlng: [10.3763, 107.1204],
    region: "Vùng Đông Nam Bộ",
  },
  {
    label: "Bạc Liêu",
    value: "Bạc Liêu",
    flag: "🇻🇳",
    latlng: [9.2850, 105.7247],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Bắc Giang",
    value: "Bắc Giang",
    flag: "🇻🇳",
    latlng: [21.2724, 106.1949],
    region: "Đông Bắc bộ",
  },
  {
    label: "Bắc Kạn",
    value: "Bắc Kạn",
    flag: "🇻🇳",
    latlng: [22.1471, 105.8342],
    region: "Đông Bắc bộ",
  },
  {
    label: "Bắc Ninh",
    value: "Bắc Ninh",
    flag: "🇻🇳",
    latlng: [21.1861, 106.0761],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Bến Tre",
    value: "Bến Tre",
    flag: "🇻🇳",
    latlng: [10.2354, 106.3754],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Bình Dương",
    value: "Bình Dương",
    flag: "🇻🇳",
    latlng: [11.1722, 106.6200],
    region: "Vùng Đông Nam Bộ",
  },
  {
    label: "Bình Định",
    value: "Bình Định",
    flag: "🇻🇳",
    latlng: [13.9497, 108.1262],
    region: "Nam Trung Bộ",
  },
  {
    label: "Bình Phước",
    value: "Bình Phước",
    flag: "🇻🇳",
    latlng: [11.7484, 106.9025],
    region: "Vùng Đông Nam Bộ",
  },
  {
    label: "Bình Thuận",
    value: "Bình Thuận",
    flag: "🇻🇳",
    latlng: [10.9334, 108.0452],
    region: "Nam Trung Bộ",
  },
  {
    label: "Cà Mau",
    value: "Cà Mau",
    flag: "🇻🇳",
    latlng: [9.1769, 105.1505],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Cao Bằng",
    value: "Cao Bằng",
    flag: "🇻🇳",
    latlng: [22.6592, 106.2519],
    region: "Đông Bắc bộ",
  },
  {
    label: "Cần Thơ",
    value: "Cần Thơ",
    flag: "🇻🇳",
    latlng: [10.7769, 106.7009],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Đà Nẵng",
    value: "Đà Nẵng",
    flag: "🇻🇳",
    latlng: [16.0544, 108.2022],
    region: "Nam Trung Bộ",
  },
  {
    label: "Đắk Lắk",
    value: "Đắk Lắk",
    flag: "🇻🇳",
    latlng: [12.6947, 108.2147],
    region: "Tây Nguyên",
  },
  {
    label: "Đắk Nông",
    value: "Đắk Nông",
    flag: "🇻🇳",
    latlng: [12.0107, 107.8329],
    region: "Tây Nguyên",
  },
  {
    label: "Điện Biên",
    value: "Điện Biên",
    flag: "🇻🇳",
    latlng: [21.3947, 103.0152],
    region: "Tây Bắc Bộ",
  },
  {
    label: "Đồng Nai",
    value: "Đồng Nai",
    flag: "🇻🇳",
    latlng: [10.9783, 107.1419],
    region: "Vùng Đông Nam Bộ",
  },
  {
    label: "Đồng Tháp",
    value: "Đồng Tháp",
    flag: "🇻🇳",
    latlng: [10.6117, 105.6266],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Gia Lai",
    value: "Gia Lai",
    flag: "🇻🇳",
    latlng: [13.9883, 108.1180],
    region: "Tây Nguyên",
  },
  {
    label: "Hà Giang",
    value: "Hà Giang",
    flag: "🇻🇳",
    latlng: [22.8268, 104.9837],
    region: "Đông Bắc bộ",
  },
  {
    label: "Hà Nam",
    value: "Hà Nam",
    flag: "🇻🇳",
    latlng: [20.5418, 105.9133],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Hà Nội",
    value: "Hà Nội",
    flag: "🇻🇳",
    latlng: [21.0285, 105.8542],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Hà Tĩnh",
    value: "Hà Tĩnh",
    flag: "🇻🇳",
    latlng: [18.3574, 105.8974],
    region: "Bắc Trung Bộ",
  },
  {
    label: "Hải Dương",
    value: "Hải Dương",
    flag: "🇻🇳",
    latlng: [20.9408, 106.3168],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Hải Phòng",
    value: "Hải Phòng",
    flag: "🇻🇳",
    latlng: [20.8449, 106.6881],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Hậu Giang",
    value: "Hậu Giang",
    flag: "🇻🇳",
    latlng: [9.7847, 105.4677],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Hòa Bình",
    value: "Hòa Bình",
    flag: "🇻🇳",
    latlng: [20.8118, 105.3382],
    region: "Tây Bắc Bộ",
  },
  {
    label: "Hưng Yên",
    value: "Hưng Yên",
    flag: "🇻🇳",
    latlng: [20.6521, 106.0511],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Khánh Hòa",
    value: "Khánh Hòa",
    flag: "🇻🇳",
    latlng: [12.2388, 109.1965],
    region: "Nam Trung Bộ",
  },
  {
    label: "Kiên Giang",
    value: "Kiên Giang",
    flag: "🇻🇳",
    latlng: [10.1204, 103.9815],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Kon Tum",
    value: "Kon Tum",
    flag: "🇻🇳",
    latlng: [14.3548, 107.9821],
    region: "Tây Nguyên",
  },
  {
    label: "Lai Châu",
    value: "Lai Chau",
    flag: "🇻🇳",
    latlng: [22.3953, 103.4520],
    region: "Tây Bắc Bộ",
  },
  {
    label: "Lạng Sơn",
    value: "Lạng Sơn",
    flag: "🇻🇳",
    latlng: [21.8456, 106.7610],
    region: "Đông Bắc bộ",
  },{
    label: "Lào Cai",
    value: "Lào Cai",
    flag: "🇻🇳",
    latlng: [22.3896, 103.9614],
    region: "Tây Bắc Bộ",
  },
  {
    label: "Lâm Đồng",
    value: "Lâm Đồng",
    flag: "🇻🇳",
    latlng: [11.9404, 108.4583],
    region: "Tây Nguyên",
  },
  {
    label: "Long An",
    value: "Long An",
    flag: "🇻🇳",
    latlng: [10.6932, 106.4161],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Nam Định",
    value: "Nam Định",
    flag: "🇻🇳",
    latlng: [20.4329, 106.1779],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Nghệ An",
    value: "Nghệ An",
    flag: "🇻🇳",
    latlng: [19.2345, 104.9200],
    region: "Bắc Trung Bộ",
  },
  {
    label: "Ninh Bình",
    value: "Ninh Bình",
    flag: "🇻🇳",
    latlng: [20.2522, 105.9750],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Ninh Thuận",
    value: "Ninh Thuận",
    flag: "🇻🇳",
    latlng: [11.8750, 108.6711],
    region: "Nam Trung Bộ",
  },
  {
    label: "Phú Thọ",
    value: "Phú Thọ",
    flag: "🇻🇳",
    latlng: [21.2764, 105.2621],
    region: "Đông Bắc bộ",
  },
  {
    label: "Phú Yên",
    value: "Phú Yên",
    flag: "🇻🇳",
    latlng: [13.1654, 109.1986],
    region: "Nam Trung Bộ",
  },
  {
    label: "Quảng Bình",
    value: "Quảng Bình",
    flag: "🇻🇳",
    latlng: [17.5497, 106.5938],
    region: "Bắc Trung Bộ",
  },{
    label: "Quảng Nam",
    value: "Quảng Nam",
    flag: "🇻🇳",
    latlng: [15.5695, 108.4808],
    region: "Nam Trung Bộ",
  },
  {
    label: "Quảng Ngãi",
    value: "Quãng Ngãi",
    flag: "🇻🇳",
    latlng: [15.1167, 108.8006],
    region: "Nam Trung Bộ",
  },
  {
    label: "Quảng Ninh",
    value: "Quảng Ninh",
    flag: "🇻🇳",
    latlng: [21.0285, 107.9775],
    region: "Đông Bắc bộ",
  },
  {
    label: "Quảng Trị",
    value: "Quảng Trị",
    flag: "🇻🇳",
    latlng: [16.7430, 107.1857],
    region: "Bắc Trung Bộ",
  },
  {
    label: "Sóc Trăng",
    value: "Sóc Trăng",
    flag: "🇻🇳",
    latlng: [9.6032, 105.9800],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Sơn La",
    value: "Sơn La",
    flag: "🇻🇳",
    latlng: [21.1533, 103.8833],
    region: "Tây Bắc Bộ",
  },
  {
    label: "Tây Ninh",
    value: "Tây Ninh",
    flag: "🇻🇳",
    latlng: [11.3060, 106.1007],
    region: "Vùng Đông Nam Bộ",
  },
  {
    label: "Thái Bình",
    value: "Thái Bình",
    flag: "🇻🇳",
    latlng: [20.4445, 106.3232],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Thái Nguyên",
    value: "Thái Nguyên",
    flag: "🇻🇳",
    latlng: [21.5949, 105.8482],
    region: "Đông Bắc bộ",
  },
  {
    label: "Thanh Hóa",
    value: "Thanh Hóa",
    flag: "🇻🇳",
    latlng: [19.8000, 105.7667],
    region: "Bắc Trung Bộ",
  },
  {
    label: "Thừa Thiên Huế",
    value: "Thừa Thiên Huế",
    flag: "🇻🇳",
    latlng: [16.4619, 107.5902],
    region: "Bắc Trung Bộ",
  },{
    label: "Tiền Giang",
    value: "Tiền Giang",
    flag: "🇻🇳",
    latlng: [10.3600, 106.3590],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "TP Hồ Chí Minh",
    value: "TP Hồ Chí Minh",
    flag: "🇻🇳",
    latlng: [10.7769, 106.7009],
    region: "Vùng Đông Nam Bộ",
  },
  {
    label: "Trà Vinh",
    value: "Trà Vinh",
    flag: "🇻🇳",
    latlng: [9.9347, 106.3439],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Tuyên Quang",
    value: "Tuyên Quang",
    flag: "🇻🇳",
    latlng: [21.8175, 105.2142],
    region: "Đông Bắc bộ",
  },
  {
    label: "Vĩnh Long",
    value: "Vĩnh Long",
    flag: "🇻🇳",
    latlng: [10.2500, 105.9667],
    region: "Vùng đồng bằng sông Cửu Long",
  },
  {
    label: "Vĩnh Phúc",
    value: "Vĩnh Phúc",
    flag: "🇻🇳",
    latlng: [21.3872, 105.5341],
    region: "Đồng bằng sông Hồng",
  },
  {
    label: "Yên Bái",
    value: "Yên Bái",
    flag: "🇻🇳",
    latlng: [21.7229, 104.9112],
    region: "Tây Bắc Bộ",
  }
]
// Create a function to format the countries data
const formatCountries = (countriesData) => {
    return countriesData.map((country) => ({
      label: country.label,
      value: country.value,
      flag: country.flag ? country.flag : '', // Check if flags exist
      region: country.region,
      latlng: country.latlng
    }));
};

const useCountries = () => {
  // Format the countries data and store it in formattedCountries
  const formattedCountries = formatCountries(countries);

  const getAll = () => formattedCountries;

  const getByValue = (value) => {
    return formattedCountries.find((country) => country.value === value);
  };

  return {
    getAll,
    getByValue,
  };
};

export default useCountries;
